### ISSUE TITLE
With Just One Wish -- Dunkelzahn's Will

### ISSUE THREAD

**Issue by LordEggNutz** [LordEggNutz/SR.Havoc.Campaign.Notes#22]
Per Big D's will

To any person who possesses a ticket stub to Maria Mercurial’s only foray into country music, performed at My Brother’s Place in the Nashville sprawl: present yourself to the Draco Foundation at any time, and the Foundation will grant you one wish. I believe the saying is, be careful what you wish for—you may well get it.

One of these such ticket stubbs was located and the Johnson would like to have it acquired so that he can get the rewards.  Problem is, the runners may decide that they would like the rewards more.

- [x] Notification
- [x] Mr Johnson: 
- [x] Job:  
- [ ] Pay:  	
- [ ] Building Details:
- [ ] Host Details:
- [ ] Additional PayData:
- [x] Twists:
- [x] Fallout:

**Comment by LordEggNutz** [comment]
To any person who possesses a ticket stub to Maria Mercurial’s only foray into country music, performed at My Brother’s Place in the Nashville sprawl: present yourself to the Draco Foundation at any time, and the Foundation will grant you one wish. I believe the saying is, be careful what you wish for—you may well get it.

One of these such ticket stubbs was located and the Johnson would like to have it acquired so that he can get the rewards. Problem is, the runners may decide that they would like the rewards more.



Notification:
Your commlink buzzes as a message comes in from your fixer, Gator. "Got an acquisition job for you, kind of a tight schedule though.  Meetin at the Rising Sun, backroom 3 at 11:30 tonight."  


Mr Johnson: 
The Johnson is a middle aged elf woman, early 30s, casually dressed in denim jeans and a t-shirt that is a size or two too small to show off her curves.  She has long blonde hair, a fair complexion and wearing a pair of black-rimmed glasses.  She is seated at the table when you arrive and stands to great you.  When she stands, she leans forward just slightly.  There are no weapons present and she is alone in the room.


The Meet:
The room is a cement walled room with no windows.  There is a sturdy table in the center with a smattering of chairs around it.  On the table is a built in white noise generator.  Once you walk into the room, you notice that you lose your Matrix connection as the room has a built in Faraday cage.


Job:  
There is a particular item that is in the possession of a private individual that the Johnson is requesting.  The item is a ticket stub to Maria Mercurial’s only foray into country music, performed at My Brother’s Place in the Nashville sprawl.  The team is to acquire the ticket stub.


Pay:  	


Building Details (if applicable):


Host Details (if applicable):


Additional PayData:


Twists:
The ticket is a counterfeit and completely worthless.  If the Johnson gets the ticket, she will hire another team to exact revenge on the runners.  If the team burns the Johnson and keeps the ticket, they may be char

Fallout:

**Comment by grazimdeoliveira** [comment]
💀
